name: Daily Commit

on:
  schedule:
    - cron: "30 5 * * *"  # Runs daily at 05:30 UTC

  workflow_dispatch:  # Allows manual trigger

jobs:
  test:
    runs-on: ubuntu-latest          # <-- This line is mandatory!
    steps:
      - name: 21f3002378@ds.study.iitm.ac.in
        run: echo "Hello, world!"
